### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by julietezekwe** [julietezekwe/shop-manager-with-deno#1]
* [ ] set up project structure server and route
* [ ] write get all user api using dummy data
* [ ] write get single user api using dummy data
* [ ] write add new user api using dummy data
* [ ] write remove single user api using dummy data
* [ ] implement validation using middle wares
* [ ] setup postgres and persist data
* [ ] implement user login (authentication)
* [ ] implement user roles Admin/users
* [ ] implement add one product
* [ ] implement get one product
* [ ] implement get all product
* [ ] implement caching with redis
* [ ] Try pubsub and queueing

### resources 
- https://dev.to/am77/deno-v1-0-303j
- https://blog.logrocket.com/creating-your-first-rest-api-with-deno-and-postgres/
- https://deno.land/manual/runtime/compiler_apis
- https://deno.land/x/oak

### further reading
...
